// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYFss5ZI8bznVj4IR8yhOnKB0PHM27E-I',
    appId: '1:78585344591:android:c7805dc3861fde9f3d303a',
    messagingSenderId: '78585344591',
    projectId: 'shop-5a159',
    authDomain: 'shop-5a159.firebaseapp.com',
    storageBucket: 'gs://shop-5a159.appspot.com',
    measurementId: 'G-ECMDFE63S7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYFss5ZI8bznVj4IR8yhOnKB0PHM27E-I',
    appId: '1:78585344591:android:c7805dc3861fde9f3d303a',
    messagingSenderId: '78585344591',
    projectId: 'shop-5a159',
    authDomain: 'shop-5a159.firebaseapp.com',
    storageBucket: 'gs://shop-5a159.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYFss5ZI8bznVj4IR8yhOnKB0PHM27E-I',
    appId: '1:78585344591:android:c7805dc3861fde9f3d303a',
    messagingSenderId: '78585344591',
    projectId: 'shop-5a159',
    authDomain: 'shop-5a159.firebaseapp.com',
    storageBucket: 'gs://shop-5a159.appspot.com',
    iosClientId: '1045475764615-sh6bdtfvq5gi9hdi9elu247v7usqsvpl.apps.googleusercontent.com',
    iosBundleId: 'com.mrezys',
  );
}
